name: Discord-Announce
on:
  push:
    branches:
      - main

jobs:
  Announce:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    uses: Ilshidur/action-discord@master
    with:
      args: 'A new commit has been pushed to `main`'
