name: Discord-Announce
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: '@Development Ping A new commit has been pushed to `main` branch of `${{github.repository}}` https://github.com/${{github.repository}}/commit/${{github.sha}}'
